### ISSUE TITLE
'Perspective Camera' is not assignable to parameter of type 'PerspectiveCamera | OrthographicCamera'.

### ISSUE THREAD

**Issue by Blakeinstein** [omanoel/three-trackballcontrols-ts#6]
Complete message trace.

> ```
> Argument of type 'PerspectiveCamera' is not assignable to parameter of type 'PerspectiveCamera | OrthographicCamera'.
>   Type 'THREE.PerspectiveCamera' is not assignable to type 'import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/cameras/PerspectiveCamera").PerspectiveCamera'.
>     The types of 'matrixWorldInverse.copy' are incompatible between these types.
>       Type '(m: THREE.Matrix4) => THREE.Matrix4' is not assignable to type '(m: import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/math/Matrix4").Matrix4) => import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/math/Matrix4").Matrix4'.
>         Types of parameters 'm' and 'm' are incompatible.
>           Type 'import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/math/Matrix4").Matrix4' is not assignable to type 'THREE.Matrix4'.
>             Types of property 'extractBasis' are incompatible.
>               Type '(xAxis: import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/math/Vector3").Vector3, yAxis: import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/math/Vector3").Vector3, zAxis: import(".../node_modules/three-...' is not assignable to type '(xAxis: THREE.Vector3, yAxis: THREE.Vector3, zAxis: THREE.Vector3) => THREE.Matrix4'.
>                 Types of parameters 'xAxis' and 'xAxis' are incompatible.
>                   Type 'THREE.Vector3' is not assignable to type 'import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/math/Vector3").Vector3'.
>                     Types of property 'copy' are incompatible.
>                       Type '(v: THREE.Vector3) => THREE.Vector3' is not assignable to type '(v: import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/math/Vector3").Vector3) => import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/math/Vector3").Vector3'.
>                         Types of parameters 'v' and 'v' are incompatible.
>                           Type 'import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/math/Vector3").Vector3' is not assignable to type 'THREE.Vector3'.
>                             Types of property 'project' are incompatible.
>                               Type '(camera: import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/cameras/Camera").Camera) => import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/math/Vector3").Vector3' is not assignable to type '(camera: THREE.Camera) => THREE.Vector3'.
>                                 Types of parameters 'camera' and 'camera' are incompatible.
>                                   Type 'THREE.Camera' is not assignable to type 'import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/cameras/Camera").Camera'.
>                                     The types of 'parent.customDepthMaterial.copy' are incompatible between these types.
>                                       Type '(material: THREE.Material) => THREE.Material' is not assignable to type '(material: import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/materials/Material").Material) => import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/materials/Material").Material'.
>                                         Types of parameters 'material' and 'material' are incompatible.
>                                           Type 'import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/materials/Material").Material' is not assignable to type 'THREE.Material'.
>                                             Types of property 'onBeforeCompile' are incompatible.
>                                               Type '(shader: import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/renderers/shaders/ShaderLib").Shader, renderer: import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/renderers/WebGLRenderer").WebGLRenderer) => void' is not assignable to type '(shader: THREE.Shader, renderer: THREE.WebGLRenderer) => void'.
>                                                 Types of parameters 'renderer' and 'renderer' are incompatible.
>                                                   Type 'THREE.WebGLRenderer' is not assignable to type 'import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/renderers/WebGLRenderer").WebGLRenderer'.
>                                                     The types of 'shadowMap.render' are incompatible between these types.
>                                                       Type '(shadowsArray: THREE.Light[], scene: THREE.Scene, camera: THREE.Camera) => void' is not assignable to type '(shadowsArray: import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/lights/Light").Light[], scene: import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/scenes/Scene").Scene, camera: import(".../node_modules/...'.
>                                                         Types of parameters 'shadowsArray' and 'shadowsArray' are incompatible.
>                                                           Type 'import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/lights/Light").Light[]' is not assignable to type 'THREE.Light[]'.
>                                                             Type 'import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/lights/Light").Light' is not assignable to type 'THREE.Light'.
>                                                               The types of 'shadow.camera.parent.normalMatrix.getInverse' are incompatible between these types.
>                                                                 Type '{ (matrix: import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/math/Matrix3").Matrix3): import(".../node_modules/three-trackballcontrols-ts/node_modules/three/src/math/Matrix3").Matrix3; (matrix: import(".../node_modules/three-t...' is not assignable to type '{ (matrix: THREE.Matrix3): THREE.Matrix3; (matrix: THREE.Matrix4, throwOnDegenerate?: boolean): THREE.Matrix3; }'.
>                                                                   Types of parameters 'matrix' and 'matrix' are incompatible.
>                                                                     Type 'Matrix4' is missing the following properties from type 'Matrix3': setFromMatrix4, getNormalMatrix, transposeIntoArray, setUvTransform, and 2 more.
> ```

Looks like an old version of three was used? As my page renders fine, yet vs-code complains.

my package.json
```
    "three": "^0.121.1",
    "three-trackballcontrols-ts": "^0.2.2",
    "typescript": "^4.0.3"
```

**Comment by omanoel** [comment]
Hi,
don't forget to say 'Hello' before writting an issue message.
You can try with the new version 0.2.3, which is loading threejs in v 0.124.0
Regards

**Comment by Blakeinstein** [comment]
My apologies!
And yes this fixed the problem, thanks!
